### PR TITLE
perf: emit timeline events only when listeners exist

### LINKED ISSUE #453: Performance: Snaping
For performance optimization would be great if the [snap](https://github.com/visjs/vis-timeline/blob/master/lib/timeline/optionsTimeline.js#L160) function would be just called on certain events, e.g. on click
It could be one additional parameter, so it would be backward-compatible.
Any thoughts on this? maybe @mojoaxel ?

### PR DESCRIPTION
**Pull request by hypery2k**
**Thank you for contributing to vis.js!!**

fixes #453

### CODE REVIEW

**Comment by luchsamapparat** [comment]
I tested the change in our project and it doesn't work:^

```
zone-evergreen.js:171 Uncaught TypeError: me.hasEventListeners is not a function
    at emit (vis-timeline-graph2d.js:26823)
    at HTMLDivElement.Timeline._this.dom.root.onmouseover [as __zone_symbol__ON_PROPERTYmouseover] (vis-timeline-graph2d.js:26843)
    at HTMLDivElement.wrapFn (zone-evergreen.js:1218)
    at ZoneDelegate.invokeTask (zone-evergreen.js:399)
    at Zone.runTask (zone-evergreen.js:167)
    at ZoneTask.invokeTask [as invoke] (zone-evergreen.js:480)
    at invokeTask (zone-evergreen.js:1621)
    at HTMLDivElement.globalZoneAwareCallback (zone-evergreen.js:1647)
```

**Comment by luchsamapparat** [comment]
... I used the wrong method name 😐

**Comment by luchsamapparat** [comment]
Fixed the method name, however there's still a weird issue in `component-emitter` 🤨

image

There's a PR for this (https://github.com/component/emitter/pull/64/files) that was rejected 🙄

**Comment by luchsamapparat** [comment]
Okay, I found the cause of this issue:

https://github.com/visjs/vis-timeline/blob/master/lib/timeline/Core.js#L145

The `listeners` property that is defined by `Core` (https://github.com/visjs/vis-timeline/blob/master/lib/timeline/Core.js#L145)  overwrites a property of the same name from `component-emitter` (https://github.com/component/emitter/blob/master/index.js#L160).

We'd probably have to rename that property in `Core` to solve this issue, but as we're in untyped JavaScript land here, I'm hesitant to make that change 😐

**Comment by yotamberk** [comment]
> Okay, I found the cause of this issue:
> 
> https://github.com/visjs/vis-timeline/blob/master/lib/timeline/Core.js#L145
> 
> The `listeners` property that is defined by `Core` (https://github.com/visjs/vis-timeline/blob/master/lib/timeline/Core.js#L145) overwrites a property of the same name from `component-emitter` (https://github.com/component/emitter/blob/master/index.js#L160).
> 
> We'd probably have to rename that property in `Core` to solve this issue, but as we're in untyped JavaScript land here, I'm hesitant to make that change 😐

You can add the change. Change `this.listeners` to `this.timelineListeners`

**Comment by luchsamapparat** [comment]
I renamed `listeners` to `timelineListeners` as you suggested and tested it locally in our project. The errors are gone as are the unnecessary calls to the snap function. So it seems the change is working as expected 🥳

**Pull request merged**
