### PR TITLE
fix: vertical-scrolling to be out of sync

### LINKED ISSUE #422: [BUG][Timeline] Vertical scroll bug on groups column and timeline
Replicable here: https://visjs.github.io/vis-timeline/examples/timeline/other/verticalScroll.html

Apr-08-2020 11-50-19

As you can see, the two columns are detached by a click + drag, also there are graphic glitches by dragging the timeline directly.

### PR DESCRIPTION
**Pull request by Sennahoi**
Fixes #422 

If vertical scrolling is enabled, scrolling on the left group panel scrolls the left and right part out of sync (see the GIF in #433). I found the following line to be the reason for this:

```
if (me._isProgramaticallyScrolled) {
        me._isProgramaticallyScrolled = false;
        return;
}
```

I removed this code and then saw a behavior I guess was the reason for this: When I scrolled down to the end of the group panel, the panel started flickering for some seconds. The reason for this flickering was that the following boundary check

```
// limit the scrollTop to the feasible scroll range
...
if (this.props.scrollTop < scrollTopMin) this.props.scrollTop = scrollTopMin;
```

used a `scrollTopMin` 2 (pixels) higher than the actual `.scrollTop` at the last scroll position.This updated the `scrollTop` property in the opposite direction the mouse scrolling did. 

The reason for these 2 pixel difference is the how the container heights are calculated. Instead of rewriting this calculation, I found it safer to just improve the `scrollTopMin` calculation to also consider the borders.

### CODE REVIEW

**Comment by Sennahoi** [comment]
What can I do to get this PR merged?

**Comment by yotamberk** [comment]
I will get to it this week

**Review by yotamberk — CHANGES_REQUESTED** [review]
I've revied this PR and it seems to do the job for fixing this issue, BUT, you've removed a fix for a different issue: 
https://github.com/visjs/vis-timeline/issues/238
Can you solve this issue with you solution?

**Comment by Sennahoi** [comment]
This is a tricky one. `dom.bottom.clientHeight` seems to oscillate between 49 and 52 px. Setting this value to 50px, the problem seems to be gone, but the code looks like there may be more inside `vis-panel vis-bottom` than just `vis-time-axis vis-foreground`.

**Comment by Sennahoi** [comment]
So, the reason for #238 seems to be the following problem:
In the `_redraw` method, the bottom height is calculated in this line

`props.bottom.height = dom.bottom.clientHeight || -props.border.bottom;`

When the bug occures, the value of clientHeight oscillates between around [49,52]. When this value changes, the other box heights are changed accordingly, which in turn triggers an update of the scrollTop position. The update triggers a redraw and for unknown reasons, clientHeight has changed which restarts the whole cycle. Interesting is that the child's height doesn't change and I don't see a padding or other style change either. 

But I found that the height in `getBoundingClientRect` doesn't change and always equals to 50. MDN says 

> This property will round the value to an integer. If you need a fractional value, use element.getBoundingClientRect().

and because not all browsers return width/height I would suggest to change the calculation as follows:

`props.bottom.height = Math.round(dom.bottom.getBoundingClientRect().height) || dom.bottom.clientHeight || -props.border.bottom;`

I changed this PR accordingly. What do you think?

**Review by yotamberk — APPROVED** [review]

**Comment by yotamberk** [comment]
Great job. Much better!

**Comment by Sennahoi** [comment]
Great that I could contribute to this project!

**Comment by yotamberk** [comment]
The pleasure is ours!

**Pull request merged**
