### PR TITLE
me.itemSet does not exit

### PR DESCRIPTION
**Pull request by estronque**

### CODE REVIEW

**Comment by estronque** [comment]
i do not see the develop branch. Fix the bug: https://github.com/visjs/vis-timeline/issues/25

**Comment by mojoaxel** [comment]
@estronque Thanks for contributing!

> i do not see the develop branch.

Sorry we need to update the PR template!

**Comment by mojoaxel** [comment]
This RP has been pre-released as [vis-timeline-eurm](https://www.npmjs.com/package/vis-timeline-eurm/v/5.1.1) by @estronque 
@yotamberk We should release v6 as soon as possible so that @estronque can deprecate [vis-timeline-eurm](https://www.npmjs.com/package/vis-timeline-eurm).

**Comment by estronque** [comment]
Fork deleted

**Pull request merged**
