### PR TITLE
fix: add mousewheel listener to top/bottom panel

### LINKED ISSUE #109: Scroll when mouse is over the time axis
Is there a way to have the "zoom on mousewheel" handler of the central timeline element also work while the mouse hovers over the time axis (or axes, if 'both' is set)? Right now the user can only scroll when hovering over the chart contents, but not when hovering over the time axes.

Would it make sense to attach the 'mousewheel' listener from https://github.com/visjs/vis-timeline/blob/master/lib/timeline/Core.js#L275 to `this.dom.bottom` and `this.dom.top` as well?

### PR DESCRIPTION
**Pull request by yotamberk**
Solves the inconsistency illustrated in #109.
fix #109

### CODE REVIEW

**Comment by yotamberk** [comment]
@Thomaash Thanks! 
Question: why are all the PRs always stuck with the `ci release` and `ci gh_pages` as pending?
It causes me to have to accept PRs with administrative privileges only every time.

**Comment by Thomaash** [comment]
You're welcome.

Regarding the forever pending checks: No branch can be merged into the master until release and gh_pages checks pass but these "checks" won't run until the branch is merged into the master :smile:. I turned these checks off. From now on it should require only the four that it actually makes sense to check.

**Comment by yotamberk** [comment]
Thanks! Just so I can learn for next time, where did you control these checks?

**Comment by Thomaash** [comment]
No problem. It's under Settings → Branches → master Edit → Require status checks to pass before merging (the under is literal in this last one, just scroll down and you'll see a light gray list of checks).

**Comment by yotamberk** [comment]
Thanks!

**Pull request merged**
