### PR TITLE
feat(build): add peer, standalone and esnext builds

### LINKED ISSUE #12: exclude moment from bundle by default?
Since #9 it is possible to exclude external libraries (e.g. moment) from the build.
The question is should be exclude e.g. `moment` by default? This would be a breaking change because than the user would always need to import `moment` manually.

What do you folks think?

### LINKED ISSUE #67: Network and Graph2d not working in the same app
We use both network and 2d charts in the same app. This worked fine in vis 4.x but no longer works. I get the following error:

`TypeError: vis.Network is not a constructor`

If the load order is 

```
        <!--Vis-->
        <script src="dist/vis-network.min.js"></script>
        <script src="dist/vis-timeline-graph2d.min.js"></script>
```
and 

`TypeError: vis.Graph2d is not a constructor`

if the graph2d module loads first. It appears like the one module overwrites the other. The last module in the load order is the one that works.

### PR DESCRIPTION
**Pull request by Thomaash**
Closes #67, closes #12.

### CODE REVIEW

**Comment by Thomaash** [comment]
Yeah, I plan to do this. This isn't done yet. It should've been a draft PR actually.

**Comment by Thomaash** [comment]
I hope I didn't forget anything. Anyway a changelog:
- Nothing was removed, that is no breaking changes here.
- Two new examples how to use the peer and standalone builds respectively.
- A note in the readme pointing to the examples for more info.
- A deprecation warning was added pointing people to the new build examples.
- The old examples have been updated to use the new standalone build.
- GH Pages in CircleCI now publishes the new dirs.
- The new builds have a new directory based API which doesn't do much in script tag URLs but is much more pleasant to use in ESM.
- The size reduction is up to 1/3. There's no reduction for people who will load the stuff anyway but a significant reduction for those who'll no longer end up with two copies of Moment and a bunch of locales they'll never use.

**Comment by Thomaash** [comment]
There's one thing I forgot. Don't merge this just yet.

**Comment by Thomaash** [comment]
Updated changelog:
- Nothing was removed, that is no breaking changes here.
- Two new examples how to use the peer and standalone builds respectively.
- A note in the readme pointing to the examples for more info.
- A deprecation warning was added pointing people to the new build examples.
- The old examples have been updated to use the new standalone build.
- GH Pages in CircleCI now publishes the new dirs.
- The new builds have a new directory based API which doesn't do much in script tag URLs but is shorter and much more pleasant to use in ESM.
- The size reduction is up to 1/3. There's no reduction for people who will load the stuff anyway but a significant reduction for those who'll no longer end up with two copies of Moment and a bunch of locales they'll never use. When the other projects are ported to the same design we'll be able to dedupe polyfills etc. for additional reduction.

**Comment by yotamberk** [comment]
Awesome work!

**Pull request merged**
