### PR TITLE
fix(timeline.setgroups): nested groups fold correcly when input is array

### LINKED ISSUE #113: Update GitHub templates
This templates need to be updated:
- [.github/ISSUE_TEMPLATE.md](https://github.com/visjs/vis-timeline/blob/master/.github/ISSUE_TEMPLATE.md)
- [.github/PULL_REQUEST_TEMPLATE.md](https://github.com/visjs/vis-timeline/blob/master/.github/PULL_REQUEST_TEMPLATE.md)

see also https://github.com/fllstx/tgw/pull/9

### PR DESCRIPTION
**Pull request by matthewstrasiotto**
# Squash preferered, HEAD is a revert of a commit that added a demo

 Fixes #113

checkout https://github.com/visjs/vis-timeline/commit/1a8fd7e26ffe7c198584a660524253cee63531e7 to see demonstration, head doesn't include this as the example isn't intended for production, and I want to expedite the review.

### CODE REVIEW

**Comment by melloware** [comment]
looks like you have a conflict?

**Comment by matthewstrasiotto** [comment]
Yeah, i guess in the last fortnight there's been some changes. 
I'd prefer the reviewer address such conflicts, if possible

**Comment by melloware** [comment]
I don't know about this project but typically that is not how it works.  You would rebase this branch and get your PR working.  Or close this PR and open another one on the latest version of the code with your fixes again.  Just my two cents...

**Comment by matthewstrasiotto** [comment]
Yeah, you're right 
I'll get around to it when I'm at a computer

**Comment by matthewstrasiotto** [comment]
Hm, the conflict looks non-trivial - I don't really understand its purpose, but it's possibly intended to address the same behaviour I am. I'll check the commit log

**Comment by matthewstrasiotto** [comment]
@Thomaash this conflicted with your commit 36e1482fe9e6f6325f7ce3af9a3f43a157ce7be4 #729 

I'd just like to confirm with you that my merge looks okay to you?

Also @yotamberk or any maintainer, when you get the chance, can you please review this?

**Review by yotamberk — APPROVED** [review]

**Comment by Thomaash** [comment]
Hi @matthewstrasiotto,

I don't think you changed my intended behavior in any meaningful way. However, even though I didn't respond on time, please don't use `instanceof Array`. The problem is that if the array comes from any other context (iframes, web workers etc.) it won't have the same Array in it's prototype chain and won't pass this check even though it is an array and works as one just fine. The function `Array.isArray(…)` would work much better.

**Comment by matthewstrasiotto** [comment]
Ah, crap, thanks for the comment @Thomaash - I'm not a JS dev, so I usually just replicate the patterns I see in the codebases I'm working on. 
Probably deserves its own PR to address that behaviour

**Comment by Thomaash** [comment]
> Ah, crap, thanks for the comment @Thomaash - I'm not a JS dev, so I usually just replicate the patterns I see in the codebases I'm working on.
> Probably deserves its own PR to address that behaviour

Yeah, it was already in the codebase. I solved all of them in #750.

**Pull request merged**
