### PR TITLE
ci: set it up

### LINKED ISSUE #42: introduce semantic versioning
see https://github.com/visjs/vis-network/issues/1

### LINKED ISSUE #44: Action required: Greenkeeper could not be activated 🚨
🚨 You need to enable Continuous Integration on Greenkeeper branches of this repository. 🚨

To enable Greenkeeper, you need to make sure that a [commit status](https://help.github.com/articles/about-statuses/) is reported on all branches. This is required by Greenkeeper because it uses your CI build statuses to figure out when to notify you about breaking changes.

Since we didn’t receive a CI status on the [`greenkeeper/initial`](https://github.com/visjs/vis-timeline/commits/greenkeeper/initial) branch, it’s possible that you don’t have CI set up yet.
We recommend using:
- [CircleCI](https://circleci.com)
- [Travis CI](https://travis-ci.org)
- [Buildkite](https://buildkite.com/)
- [CodeShip](https://codeship.com)
- [Azure Pipelines](https://azure.microsoft.com/en-us/services/devops/pipelines)
- [TeamCity](https://www.jetbrains.com/teamcity)
- [Buddy](https://buddy.works)
- [AppVeyor](https://www.appveyor.com)
But Greenkeeper will work with every other CI service as well.

If you _have_ already set up a CI for this repository, you might need to check how it’s configured. Make sure it is set to run on all new branches. If you don’t want it to run on absolutely every branch, you can whitelist branches starting with `greenkeeper/`.

Once you have installed and configured CI on this repository correctly, you’ll need to re-trigger Greenkeeper’s initial pull request. To do this, please click the 'fix repo' button on [account.greenkeeper.io](https://account.greenkeeper.io).

### PR DESCRIPTION
**Pull request by Thomaash**
Builds, tests (with coverage) and publishes if everything passes on master branch. Linting is commented out at the moment as there are 21 jsdoc comments missing or invalid (should be enabled when there are no linting issues in the code base).

Resolves #42 and resolves #44.

### CODE REVIEW

**Comment by mojoaxel** [comment]
I think @yotamberk should also have a look and say it he wants this!

**Comment by mojoaxel** [comment]
@Thomaash It looks like CI is not yet enabled for this repository. What is missing? 
@yotamberk We should try to release the v6 soon, it looks quite good: https://github.com/visjs/vis-timeline/projects/1

**Comment by Thomaash** [comment]
@mojoaxel It's indeed disabled. I don't have the permission (admin access) to enable it.

**Comment by mojoaxel** [comment]
Ah I see. I'm not sure if you want to be a full admin of the timeline as well!?
@yotamberk Is it ok with you when I give @Thomaash full admin rights?
@Thomaash Can I or @yotamberk enable cicle-ci for now?

**Comment by Thomaash** [comment]
Sure, anyone with admin access can enable it. Doesn't really matter who it is.

**Comment by Thomaash** [comment]
Configuration steps:
1. generate and set GH_TOKEN environment variable,
1. generate and set NPM_TOKEN environment variable,
1. enable building of pull requests (Settings → Advanced Settings → Build forked pull requests → On).

**Comment by mojoaxel** [comment]
Ok, I see. I just need a circleci.com account. Lets wait for [all issues for v6]( https://github.com/visjs/vis-timeline/projects/1) to be finished. I don't want a auto-release just yet...

**Pull request merged**
