### PR TITLE
fix(_updateItemsInRange) large items should not disappear

### PR DESCRIPTION
**Pull request by ctbaird**
fix(_updateItemsInRange) large items should not disappear

This is to address https://github.com/visjs/vis-timeline/issues/1573

Adds a condition to only hide items when the group is not visible and height is defined. 

The problem seems to be happening when a group is redrawn and height is temporarily `undefined`. `Group._updateItemsInRange`  is called before the group height gets defined in `redraw`. When height is undefined  in `_updateItemsInRange` , it considers the group invisible and hides the items ([lines 908-914 Group.js](https://github.com/visjs/vis-timeline/blob/master/lib/timeline/component/Group.js)). Then for the next paint, when height is defined, the group is now visible but there are no items.

### CODE REVIEW

**Comment by alexdeia** [comment]
I tested this and commented here https://github.com/visjs/vis-timeline/issues/1573#issuecomment-1497206879

**Review by yotamberk — APPROVED** [review]

**Comment by blueberryMonkeySquid** [comment]
Hi @yotamberk apologies if this is not the place to ask, but this PR fixes a big problem in my app. Is it possible for you or someone else to publish a new release with this fix?

**Comment by alexdeia** [comment]
@blueberryMonkeySquid , unfortunately, this PR didn't fix the bug completely.

**Comment by blueberryMonkeySquid** [comment]
@alexdeia thank you for the response, I see the behavior you captured in the video. Looks like it's related to vertical scrolling? The large items in my timeline disappear when I scroll horizontally. I got rid of vertical scrolling due to another bug so maybe that's why I haven't seen anything disappear after testing with this change.

**Pull request merged**
