### PR TITLE
Sequential selection feat

### PR DESCRIPTION
**Pull request by jczacharia**
The PR adds the feature: Allow **only** sequential selection of items when `sequentialSelection: true` of the timeline's configuration options.

Demo: https://next.plnkr.co/edit/2EUet6TcIoHGcH6G

### CODE REVIEW

**Comment by yotamberk** [comment]
I don;t understand this feature. Can you please elaborate?

**Comment by jczacharia** [comment]
@yotamberk This feature does not allow the user to select multiple items that are not sequential. This is a use case for when the user should not have time gaps in the items they select.

In the demo, turn `sequentialSelection` to false, then select an item all the way to the left, then hold ctrl and select an item all the way to the right. Notice that only those two are selected.

Then turn `sequentialSelection` to true. Do the same thing. Notice how all the items in between are selected now, e.g. no gaps.

**Comment by yotamberk** [comment]
Ok, I understand now.
It makes more sense to me that the holding of `Ctrl` button is non sequential while the holding of `Shift` button is sequential. It works in either way. Do you really think this feature is needed?
I feel that this feature is more specific for the `ctrl` button being held

**Comment by jczacharia** [comment]
I have a use case where the user should not be allowed to have gaps in the items they select. 
I think it's a good idea to have this feature in case other projects have this same use case.

**Comment by yotamberk** [comment]
> I have a use case where the user should not be allowed to have gaps in the items they select.

Please explain

**Comment by jczacharia** [comment]
Each item represents a task but my API only allows a user to take actions on a group of tasks where each task happens right after another. If a user were to try to take action on a group of tasks that are not next to each other, my API wouldn't process the request. So the user could go without this feature but would get confused when nothing happens to try to process non-sequential tasks. This is more of a user experience design with only processing one block of tasks at a time.

**Pull request merged**
