### PR TITLE
Make moment immutable in TimeStep and DateUtils

### PR DESCRIPTION
**Pull request by lriho**
Another step in #672 - making it possible to instantiate new Timeline with an [option moment: dayjs](https://visjs.github.io/vis-timeline/docs/timeline/#Configuration_Options) without using the [badMutable](https://day.js.org/docs/en/plugin/bad-mutable) plugin.

Basically we're trying to switch our project from Moment to DayJS and DayJS is by default immutable. This causes timeline error `Something is wrong with the Timeline scale. Limited drawing of grid lines to 1000 lines.`. So we went ahead and updated places where we noticed moment is mutating the instance.

I confirmed this locally - the error is gone and immutable DayJS works fine, gridlines are back. WDYT? What more do I need to do for this PR?

# TODO:

* [ ] Provide an additional or update an example to demonstrate your changes or new features.
* [ ] Update the documentation if you introduced new behavior or changed existing behavior.

### CODE REVIEW

**Comment by mojoaxel** [comment]
@lriho Thanks for that contribution. Sadly I can't review this merge-request because the many code-style changes. Could you please change your merge-request to just change the lines of code that realy needs changing! Thx!

**Review by mojoaxel — CHANGES_REQUESTED** [review]
@lriho Thanks for that contribution. Sadly I can't review this merge-request because the many code-style changes. Could you please change your merge-request to just change the lines of code that realy needs changing! Thx!

**Comment by lriho** [comment]
I tried to rewrite it again, but it is husky's pre-commit hook running lint-staged that adds the formatting. Anyway, ran it with --no-verify now for better readability.

**Comment by mojoaxel** [comment]
LGTM

**Review by mojoaxel — APPROVED** [review]

**Comment by lriho** [comment]
Thanks for merging this! Will you make a release with this change, so we can start using it?

**Comment by mcswanson** [comment]
Do you know when the this will be released with a replacement for moment.js?

**Pull request merged**
